config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  devise_for :users
  resources :users, only: [:show]

  resources :friends

  devise_scope :user do
   get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :events do
    get '/stream' => "events#stream"
    get '/status' => "events#status"
    resources :drones, only: [:show]
  end

  get '/sms/text_friend' => 'sms#text_friend'

  # delete "/friends/:id" => "friends#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drone.rb
class Drone < ApplicationRecord
  belongs_to :user
  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :drone
  belongs_to :user
  has_and_belongs_to_many :friends
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :events
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events
  has_many :friends
  has_many :drones
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }

  def after_sign_in_path_for(user)
      user_url(user)
  end
end

app/controllers/drones_controller.rb
class DronesController < ApplicationController

  def show
    @drone = Drone.find(params[:id])
    @user = current_user
    @friend = Friend.find(@user.friends.first.id)
    event_drone_path
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index
		@events = current_user.events.limit(8)
		@user = current_user
	end

	def new
		# render 'in-progress'
	end

	def create
		@event = Event.new(user_id: current_user.id, drone_id: 1, event_status: "not connected")

		if @event.save
			if request.xhr?
				@event.update(place_id: params["place_id"])
				render status: 200, :json => {event_id: "#{@event.id}", drone_id: "#{@event.drone.id}"}

			end
		else
			@error_messages = @event.errors.full_messages
			p @error_messages
			root_path
		end
	end

	def edit
		edit_event_path
	end

	def show
		@event = Event.find(params[:id])
		@user = User.find(@event.user.id)

		#friend variable will need to be updated
		@friend = Friend.find(@user.friends.first.id)
		event_path
	end

	def update
		p params
		@event = Event.find(params[:id])
		@event.update(event_status: params[:event_status])
	end

	def destroy
		# does user need to be able to destroy event from the events index?
	end

	def stream
		@event = Event.find(params[:event_id])
		event_stream_path
	end

	def status
		@event = Event.find(params[:event_id])
		render status: 200, :json => { event_status: @event.event_status }
	end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  def index
    @friends = current_user.friends
  end

  def create
    @friend = Friend.new(friend_params)
    @friend.user_id = current_user.id
    if @friend.save
      redirect_to @friend
    else
      render 'new'
    end
  end

  def new
  end

  def edit
    @friend = Friend.find(params[:id])
  end

  def destroy
    @friend = Friend.find(params[:id])
    @friend.destroy

    redirect_to friends_path
  end

  def show
    @friend = Friend.find(params[:id])
  end

  def update
    @friend = Friend.find(params[:id])

    if @friend.update(friend_params)
      redirect_to @friend
    else
      render 'edit'
    end
  end

  private
  
  def friend_params
    params.require(:friend).permit(:first_name, :last_name, :email, :phone_number)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/sms_controller.rb
class SmsController < ApplicationController

	def text_friend
		@user = current_user
		message = "This is " + @user.first_name + " " + @user.last_name + ". Thanks for watching that I get home safely! Link to watch: http://172.16.51.60:3000/feed"

	 	to = @user.friends.first
	 	client = Twilio::REST::Client.new(
	    	ENV["TWILIO_ACCOUNT_SID"],
	    	ENV["TWILIO_AUTH_TOKEN"]
	  	)
	  	if client.messages.create(

	    		to: "+13302070939",
	    		from: @user.phone_number,
	     		body: message
	    	)
	    	flash[:notice] = "Message has been sent!"
	  	else
	    	flash[:notice] = "Error: Message did not send"
	  	end

		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
		@user = User.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/drones/show.html.erb
<div id=top-bar>
  
  <div class=help-status id=help-not-connected>
    No one watching...
  </div>
  
</div>

<div id="main-content no-bottom">  
  <div id="walk-button">
    Walk <!-- placeholder for button to hit to keep walking -->
  </div>
  <div id="home-safely">
    Safe <!-- need proper route -->
  </div>
</div>

<script>
  var address = window.location.href;
  var split_address = address.split('/');
  var event_id = split_address[split_address.length-3];

  function statusCheck() {
    $.ajax({
      url: "/events/"+event_id+"/status"
    })
    .done(function(serverResponse) {
      console.log("success");
      console.log(serverResponse.event_status);
      if (serverResponse.event_status == "connected") {
        $(".help-status").removeAttr("id", "help-not-connected");
        $(".help-status").attr("id", "help-connected");
        $(".help-status").html("Connected")
        clearInterval(refreshElement);
      }
    })
    .fail(function(serverResponse) {
      console.log("fail")
      console.log(serverResponse)
    })
  }

  var refreshElement = setInterval(statusCheck, 5000);
</script>

app/views/events/index.html.erb
<div id="top-bar">
  Events
</div>

<div id="main-content">
  <div>
    <ul class=lists>
      <% @events.each do |event| %>
      <% date = event.created_at %>
      <% formatted_date = date.strftime("%a %B %d") %>
      <li><%= link_to formatted_date,  event_path(event) %></li>
      <%end%>
    </ul>
  </div>
</div>

<div id="bottom-bar">
  <div class=bottom-menu>
    <%= link_to "Home", user_path(current_user.id) %>
  </div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

app/views/events/show.html.erb
<div id="top-bar">

  <% date = @event.created_at %>
  <%= date.strftime("%a %B %d") %>

</div>

<div id="main-content no-bottom">
<!-- 
  <div id=user_info>
    <ul>
      <li>Phone: <%= @user.phone_number %></li>
      <li>Location: <%= @event.place_id %></li>
    </ul>
  </div> -->

  <div id=info>
    <%= @friend.first_name + " " + @friend.last_name + " " %>walked you home.
  </div>

  <div id="video">
    <iframe height=100% width=100% src="http://saved-video-feed" name="iframe_a"></iframe>
  </div>

  <div id="map">
    <iframe
      width="100%"
      height="100%"
      frameborder="0" style="border:0"
      src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAy-vo2nS3tMm9kiAE3GXSt8bU3VFOm-c4&q=<%= @event.place_id %>" allowfullscreen>
    </iframe>

  </div>
</div>

app/views/events/stream.html.erb
<div id="top-bar">

  <div class=watch-status id=help-not-connected>
    Click to let <%= @event.user.first_name %> know you're watching.
  </div>

</div>

<div id="main-content no-bottom">

	<div id=info>
		<p><%= "#{@event.user.first_name + " " + @event.user.last_name}" %></p>
    <p><%= @event.user.phone_number %></p>
    <p><span><%= @event.place_id %></span></p>
	</div>

	<div id="video">
	  <iframe height="100%" width="100%" src="http://172.16.51.60:3000/feed" name="iframe_a"></iframe>
	</div>

	<div id="map">
    <iframe
      width="100%"
      height="100%"
      frameborder="0" style="border:0"
      src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAy-vo2nS3tMm9kiAE3GXSt8bU3VFOm-c4&q=<%= @event.place_id %>" allowfullscreen>
    </iframe>
  </div>

  <div class=success-message id=hidden-div>
  	<%= @event.user.first_name %> is home.
  </div>

</div>

<script>
  var address = window.location.href;
  var split_address = address.split('/');
  var event_id = split_address[split_address.length-2];

  function statusCheck() {
    $.ajax({
      url: "/events/"+event_id+"/status"
    })
    .done(function(serverResponse) {
      console.log("success")
      console.log(serverResponse.event_status);
      if (serverResponse.event_status == "finished") {
        $("#top-bar").hide();
        $(".watch-status").hide();
        $("#info").hide();
        $("#video").hide();
        $("#map").hide();
        $(".success-message").removeAttr('id');
        $(".success-message").attr('id', 'shown-div');
        clearInterval(refreshElement);
      }
    })
    .fail(function(serverResponse) {
      console.log("fail")
      console.log(serverResponse)
    })
  }

  var refreshElement = setInterval(statusCheck, 5000);
</script>

app/views/friends/edit.html.erb
<div id="top-bar">
</div>

<div id="main-content">
  <h1>Editing friend</h1>

  <%= form_for :friend, url: friend_path(@friend), method: :put do |f| %>

  <% if @friend.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@friend.errors.count, "error") %> prevented
      this friend from being saved:
    </h2>
    <ul>
      <% @friend.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div>
    <%= form_for :friend do |f| %>
      <div class="field">
        <%= f.label :first_name, 'First Name' %><br />
        <%= f.text_field :first_name, autofocus: true %>
      </div>

      <div class="field">
        <%= f.label :last_name, 'Last Name' %><br />
        <%= f.text_field :last_name %>
      </div>

      <div class="field">
        <%= f.label :phone_number, 'Phone number' %><br />
        <%= f.text_field :phone_number %>
      </div>

      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email %>
      </div>
  </div>
</div>
  <div id="bottom-bar">
  <div class=bottom-menu>
        <div class="actions">
          <%= f.submit "Save changes" %>
        </div>
    <div class=bottom-separator></div>
    <%= link_to 'Back', friends_path %>
  </div>
  </div>



    <% end %>

  <% end %>

app/views/friends/index.html.erb
<div id="top-bar">
  Friends
</div>

<div id="main-content">
  <div>
    <ul class=lists>
      <% @friends.each do |friend| %>
      <li><%= link_to friend.first_name + friend.last_name,  friend_path(friend) %></li>
      <%end%>
    </ul>
  </div>
</div>

<div id="bottom-bar">
  <div class=bottom-menu>
    <%= link_to "Add", new_friend_path %>
  </div>
</div>

app/views/friends/new.html.erb
<div id="top-bar">
  Add friend
</div>

<div id="main-content">
  <%= form_for :friend, url: '/friends', method: :post do |f| %>
  <div class="field">
    <%= f.label :first_name, 'First Name' %><br />
    <%= f.text_field :first_name, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :last_name, 'Last Name' %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone_number, 'Phone number' %><br />
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
</div>

<div id="bottom-bar">
  <div class=bottom-menu>
    <div class="actions">
      <%= f.submit "Add friend" %>
    </div>
  </div>
</div>

  <% end %>

app/views/friends/show.html.erb
<div id="top-bar">
  Friends
</div>

<div id="main-content">
  <div id=info>
    <p><%= @friend.first_name + @friend.last_name %></p>
    <p><%= @friend.email %></p>
    <p><%= @friend.phone_number %></p>
  </div>
</div>

<div id="bottom-bar">
  <div class=bottom-menu>
    <%= link_to "Edit", edit_friend_path %>
    <div class=bottom-separator></div>
    <%= link_to "Delete", friend_path(@friend), method: :delete %>
  </div>
</div>

app/views/home/index.html.erb
<div id="main-content no-top">
  <div id="logo-space">
    <div id="logo-image">
    </div>
    <div>
      <h1>Guardian</h1>
    </div>
  </div>

</div>

<div id="bottom-bar">
  <div class="bottom-menu">
    <%= link_to 'register', new_user_registration_path %>
    <div class="bottom-separator"></div>
    <%= link_to 'login', new_user_session_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Guardian</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>


    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show-friend.html.erb
<div id="top-bar">
</div>

<div id="main-content">
</div>

<div id="bottom-bar">
</div>

<div>

<h1><%= "#{@user.first_name + " " + @user.last_name}" %></h1>


<div id=user_info>
  <ul>
  	<li>Phone: <%= @user.phone_number %></li>
  	<li>Location: </li>
  </ul>
</div>

<div id=stream>
	<iframe height="360px" width="640px" src="http://172.16.51.60:3000/feed" name="iframe_a"></iframe>
</div>


</html>

app/views/users/show.html.erb
<div id="top-bar">
  Guardian
</div>

<div id="main-content">
  <div class=location-input id=hidden-div>
    <div id="search-bar">
      <input id="pac-input" class="controls" type="text" placeholder="Enter your location">
    </div>
  </div>

  <div id=shown-div class=walk-me-home>
    Walk me home
  </div>
</div>

<div id="bottom-bar">
  <div class=bottom-menu>
    <%= link_to "Friends", friends_path %>
    <div class=bottom-separator></div>
    <%= link_to "Events", events_path %>
  </div>
</div>

<!--     <style>
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #map {
        height: 100%;
      }
      .controls {
        margin-top: 10px;
        border: 1px solid transparent;
        border-radius: 2px 0 0 2px;
        box-sizing: border-box;
        -moz-box-sizing: border-box;
        height: 32px;
        outline: none;
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
      }

      #pac-input {
        background-color: #fff;
        font-family: Roboto;
        font-size: 15px;
        font-weight: 300;
        margin-left: 12px;
        padding: 0 11px 0 13px;
        text-overflow: ellipsis;
        width: 300px;
      }

      #pac-input:focus {
        border-color: #4d90fe;
      }

      .pac-container {
        font-family: Roboto;
      }

      #type-selector {
        color: #fff;
        background-color: #4d90fe;
        padding: 5px 11px 0px 11px;
      }

      #type-selector label {
        font-family: Roboto;
        font-size: 13px;
        font-weight: 300;
      }
      #target {
        width: 345px;
      }
    </style> -->


    <script>
      function initAutocomplete() {
        var input = document.getElementById('pac-input');

        var searchBox = new google.maps.places.SearchBox(input);

        var markers = [];

        searchBox.addListener('places_changed', function() {
          var places = searchBox.getPlaces();
          if (places.length == 0) {
            return;
          }

          places.forEach(function(place) {
            if (!place.geometry) {
              console.log("Returned place contains no geometry");
              return;
            }
            $.ajax({
              url: "/events",
              method: "POST",
              data: { place_id: place.formatted_address }
            })
            .done(function(serverResponse){
              console.log(serverResponse)
              console.log(" -- This is the event-created server response");

              $('#pac-input').hide()
              $('.location-input').removeAttr('id')
              // $('.walk-me-home').removeAttr('id')
              $('.location-input').attr('id', 'hidden-div')
              // $('.walk-me-home').attr('id', 'shown-div')
              window.location.href = "/events/" + serverResponse.event_id + "/drones/" + serverResponse.drone_id;
            })
            .fail(function(serverResponse){
              console.log(serverResponse)
              console.log("New event creation failed")

            })

          });
        });

      }
    </script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAy-vo2nS3tMm9kiAE3GXSt8bU3VFOm-c4&libraries=places&callback=initAutocomplete" async defer></script>